[workspace]

members = [
  "toys/gudp-client",
  "toys/gudp-chaingun",
  "toys/gudp-echo",
  "test-harness",
  "gudp",
  "slice-pair",
  "bring",
  "cond-mutex",
  "xor",
  "clock"
]

default-members = [
  "toys/gudp-client"
]
